[workspace]
members = [
    "jiaozifs",
    "jiaozifs-models",
]
resolver = "2"


[workspace.dependencies]

serde = {version = "1",features = ["derive"]}
serde_json = "1"
serde_yaml = "0.9"
uuid = "1"
time = {version = "0.3.36"}
sea-orm = "1"
anyhow = "1"
tokio = "1"